SUBJECT_LIST = [
    ('English Literature', 'English Literature'),
    ('English Grammar', 'English Grammar'),
    ('Hindi', 'Hindi'),
    ('Sanskrit', 'Sanskrit'),
    ('Physics', 'Physics'),
    ('Chemistry', 'Chemistry'),
    ('Biology', 'Biology'),
    ('Mathematics', 'Mathematics'),
    ('Computer Science', 'Computer Science'),
    ('History & Civics', 'History & Civics'),
    ('Geography', 'Geography'),
    ('EVS', 'EVS'),
    ('GK', 'GK'),
    ('G.Sc.', 'G.Sc.'),
    ('S.St.', 'S.St.'),
    ('M.Sc.', 'M.Sc.'),
    ('SUPW', 'SUPW'),
    ('Arts', 'Arts'),
]
